server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  # 此处加可以避免抛connect异常
  rabbitmq:
    host: 192.168.0.106
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      binders:  # 配置要绑定的rabbitMQ信息
        defaultRabbit:  # 表示定义的名称，用于binding整合
          type: rabbit  # 消息组件类型
          environment:  # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.0.106
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit # 即使报红也没关系，注意缩进

eureka:
  client:
    register-with-eureka: true #是否将自己加入注册中心，默认为true
    fetch-registry: true #是否从eureka Server抓取已有的注册信息，默认为true。单节点无所谓，集群时必须设置true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7000/eureka # eureka服务地址
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2  # 设置心跳时间间隔
    instance-id: send-8801.com
    prefer-ip-address: true #访问路径改为ip地址