server:
  port: 9527

spring:
  application:
    name: cloud-payment-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route1 # 路由id，要求唯一
          # uri: http://localhost:8001  # 路由匹配后调转的地址
          uri: lb://cloud-payment-service  # 提供微服务的地址
          predicates:
            - Path=/payment/get/**  # 断言，匹配的路由
          # 此处还可配置predicate和filter

        # 访问http://localhost:9527/payment/get/** 会转发至 http://localhost:8001/payment/get/**
        - id: payment_route2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service  # 提供微服务的地址
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true #是否将自己加入注册中心，默认为true
    fetch-registry: true #是否从eureka Server抓取已有的注册信息，默认为true。单节点无所谓，集群时必须设置true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7000/eureka # eureka服务地址
      # #集群版 若是单机模拟，必须设置多个域名映射到127.0.0.1
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
