server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #是否将自己加入注册中心，默认为true
    fetch-registry: true #是否从eureka Server抓取已有的注册信息，默认为true。单节点无所谓，集群时必须设置true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7000/eureka # eureka服务地址
      #集群版 若是单机模拟，必须设置多个域名映射到127.0.0.1
#     defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka

logging:
  level:
    com.jelly.cloud.service.PaymentFeignService: debug
